root = "."
tmp_dir = "tmp"

[build]
  bin = "bin/main"
  cmd = "make build"
  delay = 1000
  exclude_dir = ["assets", "tmp"]
  exclude_unchanged = false
  include_ext = ["go"]
  log = "build-errors.log"
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
