version: '3.8'

services:
  database:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: UsersDB
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - users_sam:/var/lib/postgresql
    env_file:
      - .env

volumes:
  users_sam:
