AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DBSchema:
    Type: String
    Default: users

  DBEngine:
    Type: String
    Default: aurora-postgresql

  DBInstanceClass:
    Type: String
    Default: db.serverless

  DBMonitoringInterval:
    Type: Number
    MinValue: 0
    Default: 0

Resources:
  UsersDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: !Ref DBEngine
      DBInstanceClass: !Ref DBInstanceClass
      DBClusterIdentifier: !ImportValue DBClusterID
      MonitoringInterval: !Ref DBMonitoringInterval

Outputs:
  UsersDBInstanceHost:
    Description: "Host of the Users DB Instance"
    Value: !GetAtt UsersDBInstance.Endpoint.Address
    Export:
      Name: UsersDBInstanceHost

  UsersDBInstancePort:
    Description: "Port of the Users DB Instance"
    Value: !GetAtt UsersDBInstance.Endpoint.Port
    Export:
      Name: UsersDBInstancePort

  UsersDBInstanceSchema:
    Description: "Users DB Schema"
    Value: !Ref DBSchema
    Export:
      Name: UsersDBInstanceSchema
