name: CD Main

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  main:
    uses: ./.github/workflows/cd-template.yaml
    secrets: inherit
    with:
      environment: main

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up actions
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up SDK
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Set up release
        uses: go-semantic-release/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
