name: CD Stage

on:
  push:
    branches:
      - stage

permissions:
  id-token: write
  contents: read

jobs:
  stage:
    uses: ./.github/workflows/cd-template.yaml
    secrets: inherit
    with:
      environment: stage
