name: Stage Merge Actions

on:
  push:
    branches:
      - 'stage'

jobs:
  Config:
    runs-on: ubuntu-latest
    steps:
      - name: Set up actions
        uses: actions/checkout@v4

      # Run env validation: make config

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up actions
        uses: actions/checkout@v4

      # Build and deploy lambda
