name: CD Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  config:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Set up actions
        uses: actions/checkout@v4

      - name: Test environment
        run: echo ${{ vars.TEST }}

      # Run env validation: make config
      # Usage during run: ${{ vars.TEST }}

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Set up actions
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      # Environment: secrets, region, stack name, config function name (overrided during deploy)
      #
      # sam build config
      # sam deploy -confirm-changeset config
      # sam remote invoke ConfigFunction - fail if error
      #
      # Parallel:
      # - sam delete --stack-name --no-prompts
      #
      # - docs
      #   migrate
      #   sam build service
      #   sam deploy -confirm-changeset service
      #
      # But envoronment should be one. If not possible, then with rollback.
      # Or deploy once only function in one stack, test it, then use normal stack, using params override outputs export name
