name: Deploy Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  config:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Set up actions
        uses: actions/checkout@v4

      - name: Test environment
        run: echo ${{ vars.TEST }}

      # Run env validation: make config
      # Usage during run: ${{ vars.TEST }}

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Set up actions
        uses: actions/checkout@v4

      # Build and deploy lambda
