name: Pull Request Actions

on:
  pull_request:
    branches:
      - 'stage'

permissions:
  id-token: write
  contents: read

jobs:
  stage:
    uses: ./.github/workflows/ci-template.yaml
    secrets: inherit
    with:
      environment: stage

  # TODO: Remove when ready
  test:
    uses: ./.github/workflows/cd-template.yaml
    secrets: inherit
    with:
      environment: stage
