name: CI Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  linting:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Set up actions
        uses: actions/checkout@v4

      - name: Set up SDK
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'

      - name: Download packages
        run: go mod download

      - name: Check types
        run: make lint

      - name: Check packages
        run: go mod tidy && git diff --exit-code go.mod go.sum

      - name: Build docs
        run: make docs

      - name: Build module
        run: make build

      - name: Test environment
        run: echo "${{ vars.AWS_REGION }} ${{ secrets.AWS_ACCESS_KEY_ID  }} ${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Check templates
        run: make lint-deploy

      - name: Build service stack and changeset
        run: |
          sam build -t cfn/service.cfn.yaml
          sam deploy \
            --stack-name smartner-users-service \
            --resolve-s3 \
            --s3-prefix smartner-users-service \
            --region eu-central-1 \
            --capabilities CAPABILITY_IAM \
            --no-execute-changeset
