name: Pull Request Actions

on:
  pull_request:
    branches:
      - '**'

jobs:
  stage:
    uses: ./.github/workflows/ci-template.yaml
    with:
      environment: stage

  # TODO: Remove when ready
  # test:
  #   uses: ./.github/workflows/cd-template.yaml
  #   with:
  #     environment: stage
